In [1]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a', 'b', 'c']

minha_lista = [10, 20, 30]

arr = np.array([10, 20, 30])

d = {'a': 10, 'b': 20, 'c': 30}

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: str

In [4]:
pd.Series(data=labels, index=minha_lista)

10    a
20    b
30    c
dtype: str

In [5]:
pd.Series(labels, minha_lista)

10    a
20    b
30    c
dtype: str

In [6]:
d

{'a': 10, 'b': 20, 'c': 30}

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
ser1 = pd.Series([1,2,3,4], index = ['EUA', 'Alemanha', 'Russia', 'Japao'])

In [9]:
ser1

EUA         1
Alemanha    2
Russia      3
Japao       4
dtype: int64

In [10]:
ser2 = pd.Series([1,2,5,4], index = ['EUA', 'Alemanha', 'Italia', 'Japao'])

In [11]:
ser2

EUA         1
Alemanha    2
Italia      5
Japao       4
dtype: int64

In [12]:
ser1[['Alemanha', 'Russia']]

Alemanha    2
Russia      3
dtype: int64

In [13]:
ser1 + ser2

Alemanha    4.0
EUA         2.0
Italia      NaN
Japao       8.0
Russia      NaN
dtype: float64

In [14]:
from numpy.random import randn

In [15]:
df = pd.DataFrame(randn(5, 4), index=["A", "B", "C", "D", "E"], columns="W X Y Z".split())

In [16]:
df

          W         X         Y         Z
A  0.937972 -0.004145 -0.391838  1.931752
B -0.610012 -2.000197 -1.280264  0.101324
C -0.576040 -0.677048  0.528531 -1.113474
D  0.740250  0.457921 -0.052825  0.428988
E  1.534630 -0.737687  0.540140 -1.782747

In [18]:
df[['W']]

          W
A  0.937972
B -0.610012
C -0.576040
D  0.740250
E  1.534630

In [19]:
df["new"] = df["W"]

In [20]:
df["new"]

A    0.937972
B   -0.610012
C   -0.576040
D    0.740250
E    1.534630
Name: new, dtype: float64

In [21]:
df2 = df.drop("new", axis=1)

In [22]:
df2

          W         X         Y         Z
A  0.937972 -0.004145 -0.391838  1.931752
B -0.610012 -2.000197 -1.280264  0.101324
C -0.576040 -0.677048  0.528531 -1.113474
D  0.740250  0.457921 -0.052825  0.428988
E  1.534630 -0.737687  0.540140 -1.782747

In [23]:
df.loc[['A', 'B']]

          W         X         Y         Z       new
A  0.937972 -0.004145 -0.391838  1.931752  0.937972
B -0.610012 -2.000197 -1.280264  0.101324 -0.610012

In [24]:
df.iloc[[1, 2], [3, 4]]

          Z       new
B  0.101324 -0.610012
C -1.113474 -0.576040